language: node_js
node_js:
  - "10.15.3"
cache:
  directories:
    - node_modules
before script:
  - cd front_end
  - echo "moved to front end"
script:
  - echo "deploying"
  - yarn install
  - yarn build
branches:
  only:
    - travis
    - master
deploy:
  provider: firebase
  skip_cleanup: true
  local_dir: front_end/build
  token: $FIREBASE_TOKEN
