language: node_js
node_js:
  - "10.15.3"
cache:
  directories:
    - node_modules
script:
  - echo deploying
  - yarn build
branches:
  only:
    - travis
deploy:
  provider: firebase
  skip_cleanup: true
  local_dir: build
  token: $FIREBASE_TOKEN
