"""task session changed to session_id

Revision ID: f3f37697c066
Revises: 13f9bd5bf278
Create Date: 2019-06-09 16:10:49.159208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3f37697c066'
down_revision = '13f9bd5bf278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('session_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('task_session_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'session', ['session_id'], ['uuid'])
    op.drop_column('task', 'session')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('session', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_session_fkey', 'task', 'session', ['session'], ['uuid'])
    op.drop_column('task', 'session_id')
    # ### end Alembic commands ###
